version: '3.8'


services:

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: Eniac_Academy
      MYSQL_USER: AndreCloud
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
     - backend_network 
    

  web:
    build:
      context: .
      
    volumes:
      - .:/app
      - static_volume1:/app/static
      - static_volume2:/app/staticfiles 
     
    expose:
      - "8090"
    environment:
      - DEBUG=False
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - backend_network

  nginx:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - static_volume1:/app/static
      - static_volume2:/app/staticfiles 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - backend_network
  
volumes:
  static_volume1:
  static_volume2:
  mysql_data:

networks:
  backend_network:
    driver: bridge